### PR TITLE
Update tesseract to 4.0.0

### PR DESCRIPTION
**Pull request by igorcferreira**
This updates the in-line tesseract lib to 4.0.0

### CODE REVIEW

**Comment by igorcferreira** [comment]
It may be necessary to update the [training data](https://github.com/tesseract-ocr/tessdata/)

**Comment by xmollv** [comment]
@igorcferreira Just upgrading to 4.0.0 seems to work fine. I'm gonna update the `traineddata` too, just in case. I saw that on the link that you posted there's no `mrz`. Is that something that we own (or got from somewhere else)?

**Comment by xmollv** [comment]
Upgrading to the `eng.traineddata` from the link above makes `Tesseract` assert here:

`actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp, line 53`

🤷‍♂️

**Comment by xmollv** [comment]
I've tried with the `mrz` found [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/t7GdSDRrGpI/gMzJEcfXEAAJ) but also crashes. With [this](https://github.com/tesseract-ocr/tesseract/issues/753) `ocbr` seems to work as the current `mrz` that we have, so IDK 🤷‍♂️

**Comment by igorcferreira** [comment]
@PedroSebastiao @xmollv Any update on this? Should this PR be closed?

**Pull request closed without merging**
